parameters:
#    mtech_direct_admin_user.example.class: Mtech\DirectAdmin\UserBundle\Example

services:
#    mtech_direct_admin_user.example:
#        class: %mtech_direct_admin_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
